http:
  addr: 0.0.0.0:8010 # 默认 0.0.0.0:8000
  mode: debug # release, debug, test，默认 release
  healthz: true # 是否开启健康检查, router: /healthz，默认 true
  metrics: false # 是否开启 metrics, router: /metrics，默认 false
  profiling: false # 是否开启性能分析, router: /debug/pprof，默认 false
  ping-timeout: 10s # http 服务启动后，自检超时时间，默认 10s

apiserver: 0.0.0.0:8001 # apiserver grpc地址

redis:
  addrs:
    - "127.0.0.1:6379" # 1个addr为单节点模式，多个addrs为cluster模式
  password: "774411"
  database: 0

log:
  level: debug # 日志级别，debug, info, warn, error, dpanic, panic, fatal
  encoding: console # 输出格式，console, json
  disable-caller: true # 输出日志时是否关闭调用日志的文件和行号
  output-path: /var/log/iam-auth/iam-auth.log
  max-size: 100 # mb，日志文件最大值，超过此值会被rotated
  max-age: 30 # days，历史日志文件保留天数
  max-backups: 30 # 最大历史日志文件数
